apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  creationTimestamp: null
  name: vault-db-provider
  namespace: test
spec:
  parameters:
    objects: |
      - objectName: sql-user
        secretKey: username
        secretPath: /k8s.kubevault.com.mysql.dev.mysql-secret-engine/creds/k8s.kubevault.com.dev.readonly-role
      - objectName: sql-pass
        secretKey: password
        secretPath: /k8s.kubevault.com.mysql.dev.mysql-secret-engine/creds/k8s.kubevault.com.dev.readonly-role
    roleName: k8s.kubevault.com.demo.srb-dev-secret-r-binding
    vaultAddress: https://vault.demo:8200
    vaultSkipTLSVerify: "true"
  provider: vault
status: {}
